name = "cloudless"
author = "khazoda"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1df396ac99d81fdf9c9fe3334b0c262126a1fcbdb950cc3e5282d062681fae8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
