name = "cloudless"
author = "khazoda"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b799a2d260b0707309f2f53bd3f486fc5e6d16a881893baf454596633ef9a37c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
